name: ambulance_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_settings_screens: 0.3.3-null-safety+2
  cupertino_icons: ^1.0.6
  flutter_native_splash: '>=2.3.13'
  fluttertoast: 8.2.4
  http: 1.2.1
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  flutter_scrollbar: 1.0.0
  firebase_core: ^2.27.1  # Firebase Core (required for all Firebase services)
  firebase_auth: ^4.17.9   # Firebase Authentication
  cloud_firestore: ^4.15.9 #Cloud Firestore
  firebase_core_web: ^2.12.0
  firebase_database: ^10.4.11
  permission_handler: ^11.3.1
  shared_preferences: 2.2.2
  google_maps: ^7.1.0
  js: ^0.7.1

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/request_ambulance.jpg
    - assets/first_aid.png
    - assets/help.jpg
    - assets/history.png
    - assets/hospital.png
    - assets/splashscreen.jpg
    - assets/track.png
    - assets/login.jpg
    - assets/dashboard.jpg
    - assets/request_background.jpg
    - assets/login2.jpg
    - assets/firstaidburn.png
    - assets/firstaidacidburn.png
    - assets/firstaidbruise.jpg
    - assets/firstaidchoke.jpg
    - assets/firstaiddeepcut.jpg
    - assets/firstaiddislocation.png
    - assets/firstaidfainting.jpg
    - assets/firstaidfoodpoisoning.jpg
    - assets/firstaidfracture.png
    - assets/firstaidsnakebite.jpg
    - assets/profile.jpg

  uses-material-design: true




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
